- CONTRIBUTING.md
Contributing about yomo project
Closes #3
> docs(*): Add CONTRIBUTING

- Makefile
- README.md
- go.mod
- go.sum
- pkg/yomo/run.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/7)
> feat/deps update yomo-txtkv-codec dependency from local direcotry to github

- .github/workflows/go.yml
- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/8)
> add github build status badge to readme

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/9)
> doc(tutorial): fix quick start tutorial in readme

- internal/framework/object.go
- pkg/util/quic.go
- pkg/yomo/run.go
let golangci-lint run correctly
> chore(lint): fit for lint

- pkg/util/quic.go
Use QUIC version draft-29
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/14)
> feat(quic): set QUIC use draft-29 version and set ALPN to `hq-29`

- go.mod
- go.sum
- internal/framework/server.go
- pkg/util/quic.go
- pkg/yomo/run.go
- using json codec
- fix quic for hq-29
> feat(codec): using json codec

- go.mod
- go.sum
- pkg/util/quic.go
* Fix the problem of CPU spike %100 due to dead loop caused by incorrect judgment of Read result.
* Fix for growing cache that could lead to memory overflows
> fix(*) fix cpu , memory

- pkg/util/quic.go
happen on sess.AcceptStream when the program starting
> fix(stream): fix panic of 'No recent network activity'

- go.mod
- go.sum
for "panic: unexpected end of JSON input", update to yomo-json-codec v0.2.4
> fix(json): json parsing error

- go.mod
- go.sum
- pkg/util/quic.go
* Support for * wildcards
* Ignore the nil value returned by plugin handle
> feat(plugin): *wildcards

- pkg/util/quic.go
> fix(opt): optimize default parameters

- README_CN.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/35)
> Add Awesome QUIC to README_CN.md

- README_CN.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/38)
> Update README_CN.md of 'go get gitee.com/xxxxxx'

- README_CN.md
- awesome-quic.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/39)
> doc/quic: add learning resources

- README_CN.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/40)
> doc/quic: add Bilibili and Alibaba

- README_CN.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/43)
> doc/quic: add quic weekly

- configs/echo.go
- go.mod
- go.sum
- internal/framework/server.go
- pkg/util/quic.go
- pkg/yomo/run.go
- using yomo-codec-golang
- RunDev support OutputFormatter: HexString/PacketPrinter/EchoData/ThermometerData
close #46
> replace Codec with yomo-codec-golang

- go.mod
- go.sum
- pkg/yomo/run.go
close #56 
- optimising performance
- sticky packet handling
> update yomo-codec to v1.0.0

- go.mod
- go.sum
Solve the problem of base type encoding without wrapper node #66
> update codec to v1.1.0

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/81)
> doc: update installer script in README

- Makefile
- README.md
- internal/cmd/init.go
- internal/serverless/build.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/82)
> feat/plugin: use GOPATH to solve plugin issue

- README_CN.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/85)
> doc: update CN readme

- README_CN.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/101)
> doc: update readme

- README_CN.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/104)
> doc: update image url for gitee.com/yomorun homepage

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/110)
> doc: add documentation links

- README.md
- README_CN.md
- example/flow/app.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/112)
> refactor: update demo as Rx way

- README.md
- README_CN.md
- example/flow/app.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/114)
> chore: update examples

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/118)
> doc: add use cases

- cmd/yomo/main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/119)
> feat(zipper): Add `yomo wf dev` sub-command

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/120)
> docs: add TDengine example link

- README.md
- README_CN.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/123)
> doc: update README.md

- README.md
Please keep open before we done: https://github.com/yomorun/yomo/blob/eefa35bb442df11057a3921c0758939d32f410ff/README.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/136)
> wip: Add feature part to README

- example/flow/app.go
- example/sink/app.go
observe the key of the first data layer
> fix(example): fix example for yomo v1.0.0

- .github/release-drafter.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/141)
> chore: add release-drafter bot

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/144)
> fix: update link of Y3 in readme

- example/flow/app.go
- pkg/rx/rxstream.go
- pkg/rx/rxstream_operator.go
- Rx Operators: add `SlidingWindowWithCount` and `SlidingWindowWithTime`.
- Example: print warning message when the value reaches the threshold.
> feat(rx): Add SlidingWindow

- example/flow/app.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/152)
> feat(example): add comments and output logs

- example/multi-data-source/flow/app.go
- internal/cmd/wf/dev.go
- internal/cmd/wf/run.go
- internal/dispatcher/dispatcher.go
- internal/workflow/runtime.go
- pkg/client/client.go
- pkg/decoder/decoder.go
- pkg/rx/rxstream_operator.go
Fixed issue #171, now we only allow one stream between zipper and flow/sink.
> fix(zipper): only one stream between zipper and flow

- README.md
- README_CN.md
- example/raw-binary/README.MD
- example/raw-binary/func.go
- example/raw-binary/source.go
- go.mod
- go.sum
- pkg/client/client.go
- pkg/client/serverless.go
- pkg/decoder/decoder.go
- pkg/framing/payload.go
- pkg/logger/logger.go
- pkg/logger/zap.go
- pkg/quic/quic-go.go
- pkg/runtime/conn.go
- pkg/runtime/handler.go
- pkg/rx/rxstream_operator.go
* feat(logger): add the logger to print different level logs
* fix(decoder): support Y3 primitive packet
> feat(logger): add logger to print different level logs

- pkg/runtime/config.go
- pkg/runtime/handler.go
* decode frame before sending data to downstream zipper.
* allow empty flow/sink in zipper config.
> fix(zipper): decode frame before sending data to downstream zipper

- zipper/dispatch.go
- zipper/handler.go
Remove Rx in zipper, use the channel to pass the data to downstream stream-fn.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/226)
> refactor(zipper): remove Rx in zipper (#223)

- streamfunction/client.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/220)
> ensure CancelContext execution to avoid context leak

- zipper.go
- zipper_init.go
- zipper_init_windows.go
support for windows compile
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/245)
> feat: support windows

- example/basic/README.md
- example/basic/zipper/workflow.yaml
- example/same-stream-fn/README.MD
- update the README of `basic` example
- update the README of `same-stream-fn` example
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/254)
> fix(docs): update the README in example

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/256)
> docs(README): update the example code `app.go`

- pkg/logger/zap.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/262)
> style: logger time format

- .gitignore
- core/bridge.go
- core/client.go
- core/connector.go
- core/context.go
- core/router.go
- core/server.go
- example/Taskfile.yml
- example/websocket-bridge/client-1/main.go
- example/websocket-bridge/client-2/main.go
- example/websocket-bridge/client/main.go
- example/websocket-bridge/zipper/config.yaml
- example/websocket-bridge/zipper/main.go
- go.mod
- pkg/bridge/bridges.go
- pkg/bridge/websocket.go
- pkg/config/zipper_workflow.go
- zipper.go
- implement WebSocket bridge.
- add `bridges` section to zipper's config file to enable the WebSocket bridge.
```yaml
name: example-websocket-bridge
host: 0.0.0.0
port: 9000
functions:
- name: rand
bridges:
- name: websocket
port: 7000
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/263)
> feat(bridge): add WebSocket bridge

- core/client.go
- core/handler_type.go
- rx/runtime.go
- rx/stream.go
- rx/stream_operator.go
- sfn.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/271)
> feat(serverless): add pipe handler for streaming processing

- core/client.go
- core/server.go
- example/Taskfile.yml
- example/basic/flow/main.go
- example/basic/source/main.go
- example/basic/zipper/main.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/273)
> fix: reconnect

- core/client.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/276)
> chore: clean unnecessary files

- core/client.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/277)
> fix(core/client.go): client Write thread safety

- zipper_notwindows.go
- zipper_windows.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/281)
> fix: *nix compile

- .gitignore
- README.md
- README_CN.md
- example/1-pipeline/README.md
- example/2-iopipe/README.md
- example/README.md
- example/Taskfile.yml
- example/basic/README.md
- example/basic/sfn/main.go
- example/multi-stream-fn/README.MD
- example/multi-zipper/README.md
- example/multi-zipper/sfn/sfn_echo.go
- example/same-stream-fn/README.MD
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/285)
> docs(example): update the README in examples

- core/client.go
- pkg/logger/zap.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/293)
> fix(logger): duplication message

- core/client.go
- core/client_options.go
- example/0-basic/sfn/main.go
- example/1-pipeline/Taskfile.yml
- example/1-pipeline/go.mod
- example/1-pipeline/serverless/rand.go
- example/2-iopipe/README.md
- example/2-iopipe/Taskfile.yml
- example/2-iopipe/go.mod
- example/2-iopipe/serverless/counter.go
- example/3-multi-sfn/stream-fn-1/app.go
- example/3-multi-sfn/stream-fn-2/app.go
- example/3-multi-sfn/stream-fn-3/app.go
- example/4-cascading-zipper/sfn/sfn_echo.go
- options.go
- rx/stream_operator.go
- sfn.go
- sfn_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/291)
> refactor: rename ObservedDataTags to ObserveDataTags

- core/frame/frame.go
- core/frame/handshake_frame.go
- core/frame/handshake_frame_test.go
- core/server.go
- sfn.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/295)
> refactor(frame): rename ObservedDataTags to ObserveDataTags

- core/client.go
- core/core.go
- core/server.go
- core/stream_parser.go
- example/0-basic/Taskfile.yml
- example/0-basic/source/main.go
- example/1-pipeline/go.mod
- example/1-pipeline/go.sum
- example/2-iopipe/go.mod
- example/2-iopipe/go.sum
- go.mod
- go.sum
Related to #296 
- bump `y3` to `v1.0.5`, will not suppress io.EOF error
- client won't treat ApplicationError(0x00) as error
- server won't treat ApplicationError(0x00) as error
- need update to `v1.6.1` as bug fixed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/297)
> fix: when client close the connection, no error should occured

- README.md
- README_CN.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/298)
> docs: update readme

- zipper_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/300)
> test: zipper start/close test

- README.md
- README_CN.md
- example/0-basic/README.md
- example/1-pipeline/README.md
- example/2-iopipe/README.md
- example/3-multi-sfn/README.MD
- example/3-multi-sfn/Taskfile.yml
- example/4-cascading-zipper/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/302)
> docs(example): change CLI version to v1.0.0

- pkg/tls/tls.go
change InsecureSkipVerify to `false`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/306)
> fix: clien TLS config

- example/0-basic/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/307)
> docs(example): typos

- core/client.go
- core/listener_default.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/304)
> perf: change quic keep-alive packet strategy

- core/connector.go
- core/frame_stream.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/309)
> fix: Connector Write goroutine safety

- docs/log.md
- docs/optimizations.md
- docs/zh-cn/log.md
- docs/zh-cn/optimizations.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/305)
> docs: advanced topics

- core/client.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/311)
> fix: connection state race

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/315)
> doc: add production os performance tuning section

- core/client.go
- core/connector.go
- core/context.go
- core/core.go
- core/frame/frame.go
- core/frame/goaway_frame.go
- core/frame/rejected_frame.go
- core/frame/rejected_frame_test.go
- core/server.go
- core/stream_parser.go
- core/yerr/errors.go
- example/0-basic/sfn/main.go
- example/0-basic/source/main.go
- router.go
- sfn.go
- source.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/322)
> feat: check SFN with the same name

- core/client.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/327)
> fix: client close

- core/client.go
- core/server.go
- core/yerr/errors.go
- example/0-basic/sfn/main.go
- example/0-basic/source/main.go
- options.go
- router.go
- source.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/334)
> fix: goaway

- core/client_options.go
- core/frame/meta_frame.go
- core/server.go
- core/server_options.go
- options.go
- pkg/config/mesh_zipper.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/335)
> chore: code style

- core/frame/meta_frame.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/341)
> fix: encode metadata

- core/connection.go
- core/server.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/350)
> fix: close connection stream when client had closed

- core/server.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/351)
> fix: nil pointer error if handshake failed

- pkg/config/zipper_workflow.go
- pkg/config/zipper_workflow_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/352)
> fix(config): polish loading config and unittest

- core/client.go
update quic config
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/357)
> fix(config): QUIC config with upgrade

- README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/358)
> update installation script

- core/client.go
- core/connection.go
- core/server.go
- core/yerr/errors.go
- zipper.go
- zipper_notwindows.go
sfn reconnect
refactor connection close handler
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/360)
> fix: sfn auto reconnect/connection close

- example/1-pipeline/go.mod
- example/1-pipeline/go.sum
- example/2-iopipe/go.mod
- example/2-iopipe/go.sum
- example/4-cascading-zipper/source/source.go
- example/4-cascading-zipper/zipper-1/zipper_1.go
- example/4-cascading-zipper/zipper-2/zipper_2.go
update example & dependencies.
> chore: update example

- core/client.go
- core/core.go
- core/server.go
- core/yerr/errors.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yomorun/yomo/364)
> refactor: better client connection state management

- .github/workflows/release.yaml
- Makefile
- README_CN.md
- cli/Makefile
- cli/README_CN.md
- example/0-basic/README.md
- example/1-pipeline/README.md
- example/2-iopipe/README.md
- example/3-multi-sfn/README.MD
- example/4-cascading-zipper/README.md
- example/5-backflow/README.md
The changing of `release.yml` needs debug when do a real release.
> fix(cli): build version information loss

- cli/serverless/wasm/rust-crate/Cargo.toml
- cli/serverless/wasm/rust-crate/README.md
- cli/serverless/wasm/rust-crate/src/lib.rs
- example/7-wasm/sfn/rust/Cargo.toml
- example/7-wasm/sfn/rust/README.md
- example/7-wasm/sfn/rust/src/lib.rs
> feat: add rust crate to simplify the development of rust wasm serverless functions

- cli/serverless/wasm/wasmtime.go
- cli/serverless/wasm/wasmtime_nil.go
> chore: add build tags for wasmtime

- docs/theme.config.js
Adjust the footer style on the docs page
> docs: adjust footer style

- docs/pages/docs/_meta.json
- docs/pages/docs/api/_meta.json
- docs/pages/docs/api/sfn.mdx
- docs/pages/docs/api/source.mdx
- docs/pages/docs/api/tag.mdx
- docs/pages/docs/zipper.mdx
Previews:
- https://yomo-git-docs-source-yomorun.vercel.app/docs/zipper
- https://yomo-git-docs-source-yomorun.vercel.app/docs/api/source
- https://yomo-git-docs-source-yomorun.vercel.app/docs/api/sfn
> docs: update api docs

- cli/serverless/golang/templates/init.tmpl
- cli/serverless/golang/templates/init_rx.tmpl
- cli/serverless/golang/templates/main.tmpl
- cli/serverless/golang/templates/main_rx.tmpl
- cli/serverless/golang/templates/wasm_main.tmpl
- cli/serverless/wasm/runtime.go
- cli/serverless/wasm/serverless.go
- cli/serverless/wasm/wasmedge.go
- cli/serverless/wasm/wasmtime.go
- cli/serverless/wasm/wazero.go
- core/frame/payload_frame.go
- sfn.go
- source.go
- yomo.go
> refactor: change type of tag to uint32

- README.md
- docs/pages/docs/api/source.mdx
> docs: update API doc for #513

- cli/serverless/wasm/wasmedge.go
- cli/serverless/wasm/wasmtime.go
- cli/serverless/wasm/wazero.go
- example/2-iopipe/Taskfile.yml
optimized host module compilation
> perf: optimized host module compilation

- cli/serverless/wasm/http/http.go
- cli/serverless/wasm/wasmedge.go
- cli/serverless/wasm/wasmtime.go
- cli/serverless/wasm/wazero/http.go
- cli/serverless/wasm/wazero/memory.go
- go.mod
- go.sum
sfn handler supports http calls in the wasmtime/wasmedge runtime.
See more [#551](https://github.com/yomorun/yomo/pull/551)
> feat: http supports(wasmtime/wasmedge)

- cli/serverless/wasm/wazero.go
- go.mod
- go.sum
compatible with other wasm runtimes
> preopen PWD for wazero runtime

- docs/pages/docs/api/sfn.mdx
> doc: add sfn.Init() 

- docs/pages/docs/_meta.json
- docs/pages/docs/api/sfn.mdx
- docs/pages/docs/api/source.mdx
- docs/pages/docs/opentracing.mdx
Open Tracing docs related to PR #575
> doc: add open tracing

- LICENSE
- Makefile
- cli/build.go
- cli/dev.go
- cli/init.go
- cli/root.go
- cli/run.go
- cli/serve.go
- cli/version.go
- cmd/yomo/main.go
- core/client_options.go
- core/context.go
- core/frame/frame.go
- core/serverless/context.go
- core/ylog/slog_handler.go
- docs/pages/docs/_meta.json
- docs/pages/docs/api/sfn.mdx
- docs/pages/docs/api/source.mdx
- docs/pages/docs/opentracing.mdx
- pkg/trace/trace.go
- serverless/context.go
- serverless/guest/context.go
- serverless/guest/context_http.go
- serverless/guest/memory.go
> chore: improve comments

- example/1-pipeline/Taskfile.yml
- example/1-pipeline/serverless/rand.go
- example/2-iopipe/Taskfile.yml
- example/2-iopipe/serverless/counter.go
fix example:
- pipeline
- iopipe
> fix: example

- docs/.gitignore
- docs/next.config.mjs
- docs/public/prscd.html
> docs(prscd): add support for `go get yomo.run/prscd`

- sfn.go
- source.go
To enhance code reusability, adding the trace metadata function.
> refactor: trace metadata function

- docs/package.json
- docs/pnpm-lock.yaml
fix https://github.com/yomorun/yomo/security/dependabot/9
> fix security issue #9

- core/client_test.go
> fix(zipper):  update unit test for improve error description when auth

- LICENSE
> chore: Update LICENSE date

- core/client.go
guarantee clientID will be changed after reconnect.
> fix: server doesn't dispatch message after sfn reconnected

- pkg/bridge/ai/ai.go
- pkg/bridge/ai/provider.go
- pkg/bridge/ai/provider/azopenai/provider.go
- pkg/bridge/ai/service.go
- pkg/bridge/ai/test/ai_test.go
> fix: conn.ID() from string to uint64

- ai/model.go
- pkg/bridge/ai/api_server.go
- pkg/bridge/ai/internal/openai/apicall.go
- pkg/bridge/ai/provider/cfopenai/provider_test.go
- pkg/bridge/ai/provider/gemini/provider.go
No function call does not return an error.
> chore: remove the no function call error

- cli/serverless/golang/serverless.go
> perf: optimize yomo build speed

- example/10-ai/llm-sfn-get-weather/app.go
- example/10-ai/zipper.yaml
- pkg/bridge/ai/provider/ollama/Readme.md
- pkg/bridge/ai/service.go
Tool calls will now be included in streaming responses. [ollama 0.4.6](https://github.com/ollama/ollama/releases/tag/v0.4.6), remove the ollama patch。
> chore: remove ollama patch

- cli/serverless/nodejs/runtime.go
Check and use developer tsconfig for TypeScript compilation
> feat: use developer tsconfig for typescript compilation

- cli/build.go
- cli/cli.go
- cli/init.go
- cli/serverless/nodejs/runtime.go
- cli/serverless/nodejs/serverless.go
```sh
$ yomo init cc-test -v
⌛  Initializing the Serverless LLM Function...
✅  Congratulations! You have initialized the Serverless LLM Function successfully.
ℹ️  You can enjoy the YoMo Serverless LLM Function via the command: 
ℹ️  	cd cc-test && yomo run
$ tree cc-test 
drwxr-xr-x@   - fanweixiao 15 Apr 10:00 cc-test
.rw-r--r--@  53 fanweixiao 15 Apr 10:00 ├── .env
.rw-r--r--@  32 fanweixiao 15 Apr 10:00 ├── .gitignore
.rw-r--r--@ 391 fanweixiao 15 Apr 10:00 ├── package.json
.rw-r--r--@ 14k fanweixiao 15 Apr 10:00 ├── pnpm-lock.yaml
drwxr-xr-x@   - fanweixiao 15 Apr 10:00 ├── src
.rw-r--r--@ 612 fanweixiao 15 Apr 10:00 │   └── app.ts
.rw-r--r--@ 266 fanweixiao 15 Apr 10:00 └── tsconfig.json
```
> feat(sfn): put app.ts in src/

- cli/serverless/nodejs/runtime.go
`tsc` do not do this, so we have to do that.
> fix(cli): copy files other than .ts from src/ to dist/src/

- go.mod
- go.sum
- pkg/bridge/ai/provider/anthropic/provider.go
update anthropic-sdk-go to [v1.2.0](https://github.com/anthropics/anthropic-sdk-go/releases/tag/v1.2.0)
> chore: update anthropic-sdk-go to v1.2.0

- core/client.go
- core/client_test.go
- pkg/bridge/ai/chat.go
1. Export ParseAIFunctionDefinition
2.  Flush header after first chat
> refactor: export ParseAIFunctionDefinition
